coverage:
  status:
    project:
      default:
        target: auto
      backend:
        target: auto
        flags:
          - backend
      frontend:
        target: auto
        flags:
          - frontend
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  
  require_base: yes
  require_head: yes       
  branches: null

flags:
  backend:
    paths:
      - src/packages/backend/coverage/cobertura-coverage.xml
    carryforward: false
  frontend:
    paths:
      - src/packages/frontend/coverage/cobertura-coverage.xml
    carryforward: false