coverage:
  status:
    project:
      default:
        target: auto
      demo:
        target: auto
        flags:
          - demo
      index:
        target: auto
        flags:
          - index
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  
  require_base: yes
  require_head: yes       
  branches: null

flags:
  demo:
    paths:
      - src/packages/backend/coverage/cobertura-coverage.xml
    carryforward: true
  index:
    paths:
      - src/packages/frontend/coverage/cobertura-coverage.xml
    carryforward: true