name: Deploy to Heroku Hosting development
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  build_and_deploy_backend_development:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # install dependencies
      - run: yarn install:backend
        name: Install dependencies
      # start test
      - run: yarn test:backend:coverage
        name: Run tests
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: "${{ secrets.HEROKU_API_KEY }}"
          heroku_app_name: "${{ inputs.target }}" 
          heroku_email: "${{ secrets.HEROKU_EMAIL }}"
